name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy

      - name: Lint
        run: RUSTFLAGS="-Dwarnings" cargo clippy --all-targets --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: rustfmt

      - name: Format
        run: cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0

      - uses: taiki-e/install-action@nextest

      - name: Rust test
        run: cargo nextest run

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0

      - name: Build
        run: cargo build
